#' @title get_cubeparameters
#' @description
#' Helper function for `LagKUBE()`. 
#' The function reads tables from ACCESS to get information on which files are used and how they need to be handled. 
#' @param args arguments passed to LagKUBE
#' @return A list of relevant parameters
get_cubeparameters <- function(user_args = list()) {
  cat("\n* Henter parametre")
  parameters <- get_global_parameters()
  parameters <- c(parameters, user_args)
  parameters[["CUBEinformation"]] <- get_cube_information(parameters = parameters)
  parameters[["TNPinformation"]] <- get_tnp_information(parameters = parameters)
  parameters[["STNPinformation"]] <- get_stnp_information(parameters = parameters)
  parameters[["files"]] <- get_filenames(parameters = parameters)
  parameters[["FILFILTRE"]] <- get_filfiltre(parameters = parameters)
  parameters[["fileinformation"]] <- get_filegroup_information(parameters = parameters)
  parameters[["friskvik"]] <- get_friskvik_information(parameters = parameters)
  parameters[["HELSEREG"]] <- data.table::setDT(RODBC::sqlQuery(parameters$dbh, "SELECT * from HELSEREG", as.is = TRUE), key = c("FYLKE"))
  parameters[["KnrHarm"]] <- get_geo_recoding(parameters = parameters)
  parameters[["KB"]] <- SettKodeBokGlob(parameters = parameters)
  parameters[["Censor_type"]] <- get_censor_type(parameters = parameters)
  return(parameters)
}

#' @title get_cube_information
#' @description
#' Helper function for `get_cubeparameters()`.
#' Reads from table KUBER in the ACCESS database
#' @keywords internal
#' @noRd
#' @param name cube name
#' @param validdates valid dates to specify active rows in the ACCESS table
#' @param parameters global parameters
get_cube_information <- function(parameters){
  KUBER <- as.list(RODBC::sqlQuery(parameters$dbh, 
                                   query = paste0("SELECT * FROM KUBER WHERE KUBE_NAVN='", parameters$name, "' AND ", parameters$validdates), 
                                   as.is = TRUE))
  if(length(KUBER$KUBE_NAVN) == 0) stop("Finner ikke KUBE_NAVN='", parameters$name, "' i ACCESS::KUBER, har du skrevet riktig?")
  if((is.na(KUBER$TNP) || KUBER$TNP == "")) stop("Feltet ACCESS::KUBER::TNP er ikke satt for ", parameters$name)
  return(KUBER)
}

#' @title get_tnp_information
#' @description
#' Helper function for [get_cubeparameters()]
#' Reads from table TNP_PROD in the ACCESS database
#' @keywords internal
#' @noRd
#' @param TNPname Information from TNP column in KUBER table
#' @param validdates valid dates to specify active rows in the ACCESS table
#' @param parameters global parameters
get_tnp_information <- function(parameters){
  TNP_PROD <- as.list(RODBC::sqlQuery(parameters$dbh, 
                                      query = paste0("SELECT * FROM TNP_PROD WHERE TNP_NAVN='", parameters$CUBEinformation$TNP, "' AND ", parameters$validdates), 
                                      as.is = TRUE))
  for(col in c("TNP_NAVN", "TELLERFIL", "NEVNERFIL", "PREDNEVNERFIL")){
    TNP_PROD[[col]] <- fix_befgk_spelling(TNP_PROD[[col]])
  }
  return(TNP_PROD)
}

#' @title get_stnp_information
#' @description
#' Helper function for [get_cubeparameters()].
#' Reads from table TNP_PROD in the ACCESS database, to get information needed for standardization
#' @keywords internal
#' @noRd
#' @param TNP TNP table generated by [get_tnp_information()]
#' @param validdates valid dates to specify active rows in the ACCESS table
#' @param isrefverdiP TRUE/FALSE, is REFVERDI_VP column in KUBER table == "P", indicating if STNP is to be generated at all
#' @param isSTNP TRUE/FALSE, indicating if STNP should be different from TNP. This is indicated in the STANDARDTNFIL in TNP_PROD table.
#' @param parameters global parameters
get_stnp_information <- function(parameters){
  if(parameters$CUBEinformation$REFVERDI_VP != "P") return(list())
  if(is_empty(parameters$TNPinformation$STANDARDTNFIL)) return(parameters$TNPinformation)
  
  STNP <- as.list(RODBC::sqlQuery(parameters$dbh, 
                                  query = paste0("SELECT * FROM TNP_PROD WHERE TNP_NAVN='", parameters$TNPinformation$STANDARDTNFIL, "' AND ", parameters$validdates), 
                                  as.is = TRUE))
  return(STNP)
}

#' @title get_filenames
#' @description
#' Helper function for [get_cubeparameters()]
#' Gets a list of files specifies in the TNP_PROD table (TELLERFIL, NEVNERFIL etc.)
#' @keywords internal
#' @noRd
#' @param parameters parameters list, to access TNP and STNP with information on which files are needed
get_filenames <- function(parameters){
  files <- list()
  isteller <- is_not_empty(parameters$TNPinformation$TELLERFIL)
  if(!isteller) stop("Feltet ACCESS::TNP_PROD::TELLERFIL er ikke satt!")
  files[["TELLER"]] <- parameters$TNPinformation$TELLERFIL
  isnevnerfil <- is_not_empty(parameters$TNPinformation$NEVNERFIL)
  if(isnevnerfil) files[["NEVNER"]] <- parameters$TNPinformation$NEVNERFIL
  
  if(parameters$CUBEinformation$REFVERDI_VP == "P"){
    isprednevnerfil <- is_not_empty(parameters$TNPinformation$PREDNEVNERFIL)
    if(isprednevnerfil){
      files[["PREDNEVNER"]] <- gsub("^(.*):.*", "\\1", parameters$TNPinformation$PREDNEVNERFIL)
    } else if(isnevnerfil) {
      files[["PREDNEVNER"]] <- files$NEVNER
    } else {
      files[["PREDNEVNER"]] <- files$TELLER
    }
    
    if(is_empty(parameters$TNPinformation$STANDARDTNFIL)){
      files[["STANDARDTELLER"]] <- files$TELLER
      if(isnevnerfil) files[["STANDARDNEVNER"]] <- files$NEVNER
    } else {
      isSTNPtellerfilfil <- is_not_empty(parameters$STNPinformation$TELLERFIL)
      if(!isSTNPtellerfil) stop("Feltet ACCESS::TNP_PROD::TELLERFIL er ikke satt for STANDARDTNFIL: ", parameters$TNPinformation$STANDARDTNFIL)
      files[["STANDARDTELLER"]] <- parameters$STNPinformation$TELLERFIL
      
      isSTNPnevnerfil <- is_not_empty(parameters$STNPinformation$NEVNERFIL)
      if(isSTNPnevnerfil) files[["STANDARDNEVNER"]] <- parameters$STNPinformation$NEVNERFIL
      if(!isSTNPnevnerfil) files[["STANDARDNEVNER"]] <- parameters$STNPinformation$TELLERFIL
    }
  }
  return(files)
}

#' @title get_filfiltre
#' @description
#' Helper function for [get_cubeparameters()]
#' Reads from table FILFILTRE in the ACCESS database, to get information on special treatment of files
#' @keywords internal
#' @noRd
get_filfiltre <- function(parameters){
  filfiltre <- data.table::setDT(RODBC::sqlQuery(parameters$dbh, paste0("SELECT * FROM FILFILTRE WHERE ", parameters$validdates), as.is = TRUE))
  filfiltre <- filfiltre[FILVERSJON %in% unique(parameters$files)]
  return(filfiltre)
}

#' @title get_filegroup_information
#' @description 
#' Helper function for `get_cubeparameters()`
#' Loops through filegroups used, and uses read_filegroups_and_add_values() to get filegroup information.
#' @keywords internal
#' @noRd
#' @param files list of files to be used in the cube 
#' @param validdates valid dates to specify active rows in the ACCESS table
#' @param parameters global parameters
get_filegroup_information <- function(parameters){
  fileinfo <- list()
  
  for(file in unique(unlist(parameters$files))){
    filename <- replace_filename_if_filefilters(filename = file, filefilters = parameters$FILFILTRE)
    fileinfo[[file]] <- read_filegroups_and_add_values(filegroup = filename, parameters = parameters)
  }
  return(fileinfo)
}

#' @title replace_filename_if_filefilters
#' @keywords internal
#' @noRd
replace_filename_if_filefilters <- function(filename, filefilters){
  if(is.null(filefilters)) return(filename)
  filefilter <- filefilters[FILVERSJON == filename]
  if(nrow(filefilter) > 1) stop("> 1 rad i FILFILTRE funnet for FILVERSJON = ", filename)
  filename <- ifelse(nrow(filefilter) == 1, filefilter$ORGFIL, filename)
}

#' @title get_friskvik_information
#' @description
#' Helper function for get_cubeparameters().
#' Reads from table FRISKVIK in the ACCESS database
#' @keywords internal
#' @noRd
get_friskvik_information <- function(parameters){
  FRISKVIK <- data.table::setDT(RODBC::sqlQuery(parameters$dbh, 
                                   query = paste0(paste0("SELECT * FROM FRISKVIK WHERE AARGANG=", parameters$year, "AND KUBE_NAVN='", parameters$name, "'")), 
                                   as.is = TRUE))
  return(FRISKVIK)
}

#' @title get_filedesign
#' @keywords internal
#' @noRd
#' @param parameters global parameters
get_filedesign <- function(parameters){
  if(!exists("BUFFER", envir = .GlobalEnv)) stop("BUFFER does not exist, files not loaded")
  filedesign <- list()
  files <- unique(parameters$files)
  for(file in files){
    if(is.null(.GlobalEnv$BUFFER[[file]])) stop("File ", file, " is not loaded into BUFFER")
    filedesign[[file]] <- find_filedesign(filename = file, parameters = parameters)
  }
  return(filedesign)
}

#' @title set_predictionfilter (kb)
#' @description 
#' Helper function for `get_cubeparameters()`
#' @keywords internal
#' @noRd
#' @param REFVERDI Corresponds to ACCESS::KUBER::REFVERDI
#' @param parameters global parameters
set_predictionfilter <- function(parameters) {
  refverdi <- parameters$CUBEinformation$REFVERDI
  tellerfile <- parameters$files$TELLER
  maxaar <- max(BUFFER[[tellerfile]]$AARh)
  movav <- ifelse(is_not_empty(parameters$CUBEinformation$MOVAV), parameters$CUBEinformation$MOVAV, 1) 
  if(is_empty(refverdi)) stop("Kolonnen KUBER::REFVERDI er tom, denne må settes!")
  
  out <- list(Design = list())
  delkolN <- parameters$DefDesign$DelKolN
  refverdicolumns <- delkolN[sapply(delkolN, grepl, refverdi)]
  if(!"Gn" %in% names(refverdicolumns)){
    refverdicolumns <- c(setNames("L", "Gn"), refverdicolumns)
    refverdi <- paste("GEOniv=='L'", refverdi, sep = " & ")
  }
  out[["Predfiltercolumns"]] <- as.character(unlist(parameters$DefDesign$DelKolsF[names(refverdicolumns)]))
  out[["ref_year_type"]] <- ifelse(grepl("AAR", refverdi), "Specific", "Moving")
  meisskalafilter <- character()
  
  for (del in names(refverdicolumns)) {
    delN <- refverdicolumns[del]
    if(del == "Gn"){
      val <- gsub(paste0(".*", delN, " *== *\'(.*?)\'.*"), "\\1", refverdi)
      out$Design[[del]] <- data.table::setDT(setNames(as.list(val), delN))
      meisfilter <- paste0("GEOniv == '", val, "'")
      meisskalafilter <- c(meisskalafilter, meisfilter)
    }
    
    if(del == "Y"){
      aar <- as.numeric(ifelse(grepl("AAR[lh]*=='siste'", refverdi, ignore.case = TRUE), maxaar, gsub(paste0(".*AAR[lh]*== *\'(.*?)\'.*"), "\\1", refverdi)))
      if(is_not_empty(movav) && movav > 1){
        if(grepl("AAR[lh]*=='siste'|AARh", refverdi, ignore.case = TRUE)){
          aar <- (aar-movav+1):aar
        } else if(grepl("AARl", refverdi)){
          aar <- aar:(aar+movav-1)
        }
      } 
      out$Design[[del]] <- data.table::setDT(setNames(list(aar, aar), c("AARl", "AARh")))
      meisfilter <- paste0("AARh == '", max(aar), "'")
      meisskalafilter <- c(meisskalafilter, meisfilter)
    }
  }
  out[["meisskalafilter"]] <- paste(meisskalafilter, collapse = " & ")
  return(out)
}

#' @title update_cubedesign_after_moving_average
#' @description
#' updates cubedesign after aggregating to moving average. Changes the year part, to reflect periods. 
#' This is crucial when recoding predteller before merging onto cube. 
#' @keywords internal
#' @noRd
#' @param dt cube
#' @param origdesign Cubedesign after merging teller and nevner. 
update_cubedesign_after_moving_average <- function(dt, origdesign, parameters){
  if(!parameters$MOVAVparameters$is_movav) return(origdesign)
  aar <- unique(dt[, mget(c("AARl", "AARh"))])
  origdesign$Y <- aar
  return(origdesign)
}

#' @title get_geo_recoding
#' @description Fetches geo recoding table (KnrHarm) from ACCESS
#' @keywords internal
#' @noRd
get_geo_recoding <- function(parameters){
  KnrHarm <- data.table::setDT(RODBC::sqlQuery(parameters$dbh, "SELECT * from KnrHarm", as.is = TRUE), key = c("GEO"))
  KnrHarmS <- data.table::copy(KnrHarm)[, let(GEO = paste0(GEO, "00"), GEO_omk = paste0(GEO_omk, "00"))]
  return(data.table::rbindlist(list(KnrHarm, KnrHarmS)))
}

#' @title SettKodeBokGlob
#' @author Kåre Bævre
#' @param parameters global parameters
#' @keywords internal
#' @noRd
SettKodeBokGlob <- function(parameters) {
  OmkodD <- data.table::setDT(RODBC::sqlQuery(parameters$dbh, "SELECT * FROM KH_OMKOD
                                              UNION SELECT ID, DEL, KODE as NYKODE, KODE as ORGKODE, 0 as PRI_OMKOD, 1 AS OBLIG FROM KH_KODER", as.is = TRUE))
  OmkodD <- OmkodD[DEL != "S"]
  KB <- list()
  
  for (del in names(parameters$DefDesign$DelKolN)) {
    KBD <- OmkodD[DEL == del]
    if (parameters$DefDesign$DelType[del] == "INT") {
      if (nrow(KBD) > 0) {
        KBD[, c("ORGKODEl", "ORGKODEh", "NYKODEl", "NYKODEh") := NA_integer_]
      } else {
        KBD[, c("ORGKODEl", "ORGKODEh", "NYKODEl", "NYKODEh") := integer()]
      }
    } else if (parameters$DefDesign$DelFormat[del] == "integer") {
      if(del == "L") KBD <- KBD[!grepl("[^0-9]", ORGKODE)]
      KBD[, names(.SD) := lapply(.SD, as.integer), .SDcols = c("ORGKODE", "NYKODE")]
    }
    kbdnames <- names(KBD)
    kbdnames <- gsub("ORGKODE", parameters$DefDesign$DelKolN[del], kbdnames)
    kbdnames <- gsub("NYKODE(h|l|)", paste0(parameters$DefDesign$DelKolN[del], "\\1_omk"), kbdnames)
    kbdnames <- gsub("NYKODE(h|l|)", paste0(parameters$DefDesign$DelKolN[del], "\\1_omk"), kbdnames)
    kbdnames <- gsub("PRI_OMKOD", paste0(del, "_pri"), kbdnames)
    kbdnames <- gsub("OBLIG", paste0(del, "_obl"), kbdnames)
    data.table::setnames(KBD, names(KBD), kbdnames)
    KBD[, c("ID", "DEL") := NULL]
    KB[[del]] <- KBD
  }
  return(KB)
}

#' @keywords internal
#' @noRd
get_censor_type <- function(parameters){
  stataVar <- c("Stata_PRIKK_T", "Stata_PRIKK_N", "Stata_STATTOL_T")
  RprikkVar <- c("PRIKK_T", "PRIKK_N", "STATTOL_T")
  spc <- data.table::as.data.table(parameters$CUBEinformation)[, .SD, .SDcols = c(stataVar, RprikkVar)]
  r <- sum(sapply(spc[, ..RprikkVar], get_col), na.rm = TRUE)
  s <- sum(sapply(spc[, ..stataVar], get_col), na.rm = TRUE)
  if(r > 0 & s > 0) stop("You can't prikk for both R and Stata way. Choose either one in ACCESS::KUBER!")
  if(r > 0) return("R")
  if(s > 0) return("STATA")
  return(invisible(NULL))
}

#' @keywords internal
#' @noRd
get_col <- function(var, num = TRUE){
  if(is.na(var) || var == "") var <- NA
  if(num) var <- var_num(var)
  if(!is.na(var) && num) var <- 1
  return(var)
}

#' @keywords internal
#' @noRd
var_num <- function(x){
  if(!is.numeric(x)) x <- NA
  return(x)
}