#' @title get_cubeparameters
#' @description
#' Helper function for `LagKUBE()`. 
#' The function reads tables from ACCESS to get information on which files are used and how they need to be handled. 
#' @param KUBEid name of cube
#' @param batchdate date of current cube batch. Needed to filter out active parameters from ACCESS
#' @param globs global parameters, defaults to SettGlobs
#' @return A list of relevant parameters
get_cubeparameters <- function(KUBEid, batchdate = SettKHBatchDate(), globs = SettGlobs()) {
  cat("* Henter parametre")
  parameters <- list()
  parameters[["validdates"]] <- paste0("VERSJONFRA <=", FormatSqlBatchdate(batchdate), " AND VERSJONTIL >", FormatSqlBatchdate(batchdate))
  parameters[["CUBEinformation"]] <- get_cube_information(KUBEid = KUBEid, validdates = parameters$validdates, globs = globs)
  parameters[["TNPinformation"]] <- get_tnp_information(TNPname = parameters$CUBEinformation$TNP, validdates = parameters$validdates, globs = globs)
  isrefverdiP <- parameters$CUBEinformation$REFVERDI_VP == "P"
  isSTNP <- is_not_empty(parameters$TNPinformation$STANDARDTNFIL)
  parameters[["STNPinformation"]] <- get_stnp_information(TNP = parameters$TNPinformation, validdates = parameters$validdates, isrefverdiP = isrefverdiP, isSTNP = isSTNP, globs = globs)
  parameters[["files"]] <- get_filenames(parameters = parameters, isrefverdiP = isrefverdiP, isSTNP = isSTNP)
  parameters[["FILFILTRE"]] <- get_filfiltre(files = parameters$files, validdates = parameters$validdates, globs = globs)
  parameters[["ref_year_type"]] <- parameters$PredFilter$ref_year_type
  parameters[["fileinformation"]] <- get_filegroup_information(files = parameters$files, filefilters = parameters$FILFILTRE, validdates = parameters$validdates, globs = globs)
  parameters[["friskvik"]] <- get_friskvik_information(KUBEid = KUBEid, globs = globs)
  return(parameters)
}

#' @title get_cube_information
#' @description
#' Helper function for `get_cubeparameters()`.
#' Reads from table KUBER in the ACCESS database
#' @noRD
#' @param KUBEid cube name
#' @param validdates valid dates to specify active rows in the ACCESS table
#' @param globs global parameters, defaults to SettGlobs
get_cube_information <- function(KUBEid, validdates, globs){
  KUBER <- as.list(RODBC::sqlQuery(globs$dbh, 
                                   query = paste0("SELECT * FROM KUBER WHERE KUBE_NAVN='", KUBEid, "' AND ", validdates), 
                                   as.is = TRUE))
  if(length(KUBER$KUBE_NAVN) == 0) stop("Finner ikke KUBE_NAVN='", KUBEid, "' i ACCESS::KUBER, har du skrevet riktig?")
  if((is.na(KUBER$TNP) || KUBER$TNP == "")) stop("Feltet ACCESS::KUBER::TNP er ikke satt for ", KUBEid)
  return(KUBER)
}

#' @title get_tnp_information
#' @description
#' Helper function for [get_cubeparameters()]
#' Reads from table TNP_PROD in the ACCESS database
#' @noRD
#' @param TNPname Information from TNP column in KUBER table
#' @param validdates valid dates to specify active rows in the ACCESS table
#' @param globs global parameters, defaults to SettGlobs
get_tnp_information <- function(TNPname, validdates, globs){
  TNP_PROD <- as.list(RODBC::sqlQuery(globs$dbh, 
                                      query = paste0("SELECT * FROM TNP_PROD WHERE TNP_NAVN='", TNPname, "' AND ", validdates), 
                                      as.is = TRUE))
  return(TNP_PROD)
}

#' @title get_stnp_information
#' @description
#' Helper function for [get_cubeparameters()].
#' Reads from table TNP_PROD in the ACCESS database, to get information needed for standardization
#' @noRD
#' @param TNP TNP table generated by [get_tnp_information()]
#' @param validdates valid dates to specify active rows in the ACCESS table
#' @param isrefverdiP TRUE/FALSE, is REFVERDI_VP column in KUBER table == "P", indicating if STNP is to be generated at all
#' @param isSTNP TRUE/FALSE, indicating if STNP should be different from TNP. This is indicated in the STANDARDTNFIL in TNP_PROD table.
#' @param globs global parameters, defaults to SettGlobs
get_stnp_information <- function(TNP, validdates, isrefverdiP = F, isSTNP = F, globs){
  if(!isrefverdiP) return(list())
  if(!isSTNP) return(TNP)
  
  STNP <- as.list(RODBC::sqlQuery(globs$dbh, 
                                  query = paste0("SELECT * FROM TNP_PROD WHERE TNP_NAVN='", TNP$STANDARDTNFIL, "' AND ", validdates), 
                                  as.is = TRUE))
  return(STNP)
}

#' @title get_filenames
#' @description
#' Helper function for [get_cubeparameters()]
#' Gets a list of files specifies in the TNP_PROD table (TELLERFIL, NEVNERFIL etc.)
#' @param parameters parameters list, to access TNP and STNP with information on which files are needed
#' @param isrefverdiP TRUE/FALSE, is REFVERDI_VP column in KUBER table == "P", indicating if standard files should be included
#' @param isSTNP TRUE/FALSE, indicating if standard files should be different from the main files. This is indicated in the STANDARDTNFIL in TNP_PROD table.
get_filenames <- function(parameters, isrefverdiP, isSTNP = F){
  files <- list()
  isteller <- is_not_empty(parameters$TNPinformation$TELLERFIL)
  if(!isteller) stop("Feltet ACCESS::TNP_PROD::TELLERFIL er ikke satt!")
  files[["TELLER"]] <- parameters$TNPinformation$TELLERFIL
  isnevnerfil <- is_not_empty(parameters$TNPinformation$NEVNERFIL)
  if(isnevnerfil) files[["NEVNER"]] <- parameters$TNPinformation$NEVNERFIL
  
  if(isrefverdiP){
    isprednevnerfil <- is_not_empty(parameters$TNPinformation$PREDNEVNERFIL)
    if(isprednevnerfil){
      files[["PREDNEVNER"]] <- gsub("^(.*):.*", "\\1", parameters$TNPinformation$PREDNEVNERFIL)
    } else if(isnevnerfil) {
      files[["PREDNEVNER"]] <- files$NEVNER
    } else {
      files[["PREDNEVNER"]] <- files$TELLER
    }
    
    if(!isSTNP){
      files[["STANDARDTELLER"]] <- files$TELLER
      if(isnevnerfil) files[["STANDARDNEVNER"]] <- files$NEVNER
    } else {
      isSTNPtellerfilfil <- is_not_empty(parameters$STNPinformation$TELLERFIL)
      if(!isSTNPtellerfil) stop("Feltet ACCESS::TNP_PROD::TELLERFIL er ikke satt for STANDARDTNFIL: ", parameters$TNPinformation$STANDARDTNFIL)
      files[["STANDARDTELLER"]] <- parameters$STNPinformation$TELLERFIL
      
      isSTNPnevnerfil <- is_not_empty(parameters$STNPinformation$NEVNERFIL)
      if(isSTNPnevnerfil) files[["STANDARDNEVNER"]] <- parameters$STNPinformation$NEVNERFIL
      if(!isSTNPnevnerfil) files[["STANDARDNEVNER"]] <- parameters$STNPinformation$TELLERFIL
    }
  }
  return(files)
}

#' @title get_filfiltre
#' @description
#' Helper function for [get_cubeparameters()]
#' Reads from table FILFILTRE in the ACCESS database, to get information on special treatment of files
#' @param files list of files generated by [get_filenames()]
#' @param validdates valid dates to specify active rows in the ACCESS table
#' @param globs global parameters, defaults to SettGlobs
get_filfiltre <- function(files = NULL, validdates, globs){
  filfiltre <- data.table::setDT(RODBC::sqlQuery(globs$dbh, paste0("SELECT * FROM FILFILTRE WHERE ", validdates), as.is = TRUE))
  filfiltre <- filfiltre[FILVERSJON %in% unique(files)]
  return(filfiltre)
}

#' @title get_filegroup_information
#' @description 
#' Helper function for `get_cubeparameters()`
#' Loops through filegroups used, and uses read_filgrupper_and_add_vals() to get filegroup information.
#' @noRD
#' @param files list of files to be used in the cube 
#' @param validdates valid dates to specify active rows in the ACCESS table
#' @param globs global parameters, defaults to SettGlobs
get_filegroup_information <- function(files, filefilters = NULL, validdates, globs = SettGlobs()){
  fileinfo <- list()
  
  for(file in unique(files)){
    filename <- replace_filename_if_filefilters(filename = file, filefilters = filefilters)
    fileinfo[[file]] <- read_filgrupper_and_add_vals(filegroup_name = filename, validdates = validdates, globs = globs)
  }
  return(fileinfo)
}

#' @noRd
replace_filename_if_filefilters <- function(filename, filefilters){
  if(is.null(filefilters)) return(filename)
  filefilter <- filefilters[FILVERSJON == filename]
  if(nrow(filefilter) > 1) stop("> 1 rad i FILFILTRE funnet for FILVERSJON = ", filename)
  filename <- ifelse(nrow(filefilter) == 1, filefilter$ORGFIL, filename)
}

#' @title get_friskvik_information
#' @description
#' Helper function for get_cubeparameters().
#' Reads from table FRISKVIK in the ACCESS database
#' @noRD
#' @param KUBEid cube name
#' @param globs global parameters, defaults to SettGlobs
get_friskvik_information <- function(KUBEid, globs){
  FRISKVIK <- data.table::setDT(RODBC::sqlQuery(globs$dbh, 
                                   query = paste0(paste0("SELECT * FROM FRISKVIK WHERE AARGANG=", getOption("khfunctions.year"), "AND KUBE_NAVN='", KUBEid, "'")), 
                                   as.is = TRUE))
  return(FRISKVIK)
}

#' @title get_filedesign
#' @description
#' @noRD
#' @param files 
#' @param parameters 
#' @param globs global parameters, defaults to SettGlobs
get_filedesign <- function(parameters, globs){
  if(!exists("BUFFER", envir = .GlobalEnv)) stop("BUFFER does not exist, files not loaded")
  filedesign <- list()
  files <- unique(parameters$files)
  for(file in files){
    if(is.null(.GlobalEnv$BUFFER[[file]])) stop("File ", file, " is not loaded into BUFFER")
    fileinfo <- parameters$fileinformation[[file]]
    filedesign[[file]] <- find_filedesign(file = .GlobalEnv$BUFFER[[file]], fileparameters = fileinfo, globs = globs)
  }
  return(filedesign)
}

#' @title set_predictionfilter (kb)
#' @description 
#' Helper function for `get_cubeparameters()`
#' @param REFVERDI Corresponds to ACCESS::KUBER::REFVERDI
#' @param globs global parameters, defaults to SettGlobs
set_predictionfilter <- function(parameters, globs) {
  refverdi <- parameters$CUBEinformation$REFVERDI
  tellerfile <- parameters$files$TELLER
  maxaar <- max(BUFFER[[tellerfile]]$AARh)
  movav <- parameters$CUBEinformation$MOVAV
  if(is_empty(refverdi)) stop("Kolonnen KUBER::REFVERDI er tom, denne må settes!")
  
  out <- list(Design = list())
  delkolN <- globs$DefDesign$DelKolN
  refverdicolumns <- delkolN[sapply(delkolN, grepl, refverdi)]
  out[["Predfiltercolumns"]] <- as.character(unlist(globs$DefDesign$DelKolsF[names(refverdicolumns)]))
  out[["ref_year_type"]] <- ifelse(grepl("AAR", refverdi), "Specific", "Moving")
  meisskalafilter <- character()
  
  for (del in names(refverdicolumns)) {
    delN <- refverdicolumns[del]
    if(del == "Gn"){
      val <- gsub(paste0(".*", delN, " *== *\'(.*?)\'.*"), "\\1", refverdi)
      out$Design[[del]] <- data.table::setDT(setNames(as.list(val), delN))
      meisfilter <- paste0("GEOniv == '", val, "'")
      meisskalafilter <- c(meisskalafilter, meisfilter)
    }
    
    if(del == "Y"){
      aar <- as.numeric(ifelse(grepl("siste", refverdi), maxaar, gsub(paste0(".*AAR[lh]*== *\'(.*?)\'.*"), "\\1", refverdi)))
      if(movav > 1) aar <- (aar-movav+1):aar
      out$Design[[del]] <- data.table::setDT(setNames(list(aar, aar), c("AARl", "AARh")))
      meisfilter <- paste0("AARh == '", max(aar), "'")
      meisskalafilter <- c(meisskalafilter, meisfilter)
    }
  }
  out[["meisskalafilter"]] <- paste(meisskalafilter, collapse = " & ")
  return(out)
}

#' @title update_cubedesign_after_moving_average
#' @description
#' updates cubedesign after aggregating to moving average. Changes the year part, to reflect periods. 
#' This is crucial when recoding predteller before merging onto cube. 
#'
#' @param dt cube
#' @param origdesign Cubedesign after merging teller and nevner. 
#' @noRd
update_cubedesign_after_moving_average <- function(dt, origdesign, parameters){
  if(!parameters$MOVAVparameters$is_movav) return(origdesign)
  aar <- unique(dt[, mget(c("AARl", "AARh"))])
  origdesign$Y <- aar
  return(origdesign)
}
