globglobs <- list(
  HOVEDmodus = "NH",
  KHaargang = 2023,
  KHgeoniv = "K",
  KHdbname = dbNameFile,
  KHlogg = dbLogFile,
  StablaDirNy = "PRODUKTER/MELLOMPROD/R/STABLAORG/NYESTE",
  StablaDirDat = "PRODUKTER/MELLOMPROD/R/STABLAORG/DATERT",
  KubeDir_NH = "PRODUKTER/KUBER/NORGESHELSA",
  KubeDirNy_NH = "PRODUKTER/KUBER/NORGESHELSA/NYESTE/R",
  KubeDirDat_NH = "PRODUKTER/KUBER/NORGESHELSA/DATERT",
  KubeDirQC_NH = "PRODUKTER/KUBER/NORGESHELSA/QC",
  KubeDir_KH = "PRODUKTER/KUBER/KOMMUNEHELSA",
  KubeDirNy_KH = "PRODUKTER/KUBER/KOMMUNEHELSA/NYESTE/R",
  KubeDirDat_KH = "PRODUKTER/KUBER/KOMMUNEHELSA/DATERT",
  KubeDirQC_KH = "PRODUKTER/KUBER/KOMMUNEHELSA/QC",
  KubeStataPrikkFil ="BIN/Z_Statasnutter/StataPrikking.do",
  FriskVDir_F = "PRODUKTER/KUBER/FRISKVIK_FYLKE",
  FriskVDir_K = "PRODUKTER/KUBER/FRISKVIK_KOMM",
  FriskVDir_B = "PRODUKTER/KUBER/FRISKVIK_BYDEL",
  ovpDir_F = "PRODUKTER/KUBER/OVP_FYLKE/",
  ovpDir_K = "PRODUKTER/KUBER/OVP_KOMM/",
  ovpDir_B = "PRODUKTER/KUBER/OVP_BYDEL/",
  TNPDirNy = "PRODUKTER/MELLOMPROD/R/TNP/NYESTE",
  TNPDirDat = "PRODUKTER/MELLOMPROD/R/TNP/DATERT",
  BUFFERdir = "BIN/BUFFER",
  DUMPdir = "RUNTIMEDUMP",
  kolorgs = c("GEO", "AAR", "KJONN", "ALDER", "UTDANN", "INNVKAT", "LANDBAK", "TAB1", "TAB2", "TAB3", "VAL1", "VAL2", "VAL3"),
  taborgs = c("GEO", "AAR", "KJONN", "ALDER", "TAB1", "TAB2", "TAB3"),
  NesstarOutputDef = c(MT = "MALTALL", T = "TELLER", N = "NEVNER", RATE = "RATE", SMR = "SMR", MEIS = "MEIS", ST = "sumTELLER", SN = "sumNEVNER", SPT = "sumPREDTELLER", RN = "RATE.n"),
  FriskvikTabs = c("GEO", "AAR", "KJONN", "ALDER", "UTDANN", "INNVKAT", "LANDBAK", "ETAB"),
  FriskvikVals = c("sumTELLER", "sumNEVNER", "RATE", "MALTALL", "sumPREDTELLER", "PREDTELLER", "SMR", "NORM", "MEIS", "RATE.n"),
  QCTabs = c("GEO", "GEOniv", "AAR", "KJONN", "ALDER", "UTDANN", "INNVKAT", "LANDBAK"), 
  QCVals = c("TELLER", "NEVNER", "RATE", "RATE.n", "SMR", "MEIS", "NORM", "MALTALL", "sumTELLER", "sumNEVNER", "PREDTELLER", "sumPREDTELLER"),
  KubeKols = c("sumTELLER", "sumNEVNER", "RATE", "MALTALL", "sumPREDTELLER", "PREDTELLER", "SMR", "NORM", "MEIS", "RATE.n", "ALDER", "AAR", "SMRtmp"),
  binDir = "bin",
  tmpfilerpath = "bin\tmpfiler",
  geo_illeg = "GGG",
  alder_illeg = "888_888",
  alder_ukjent = "999_999",
  kjonn_illeg = "8",
  kjonn_ukjent = "9",
  aar_illeg = "8888_8888",
  utdann_illeg = "8",
  utdann_ukjent = "9",
  landbak_illeg = "8",
  landbak_ukjent = "9",
  innvkat_illeg = "8",
  innvkat_ukjent = "9",
  SisteBatch = "9999-01-01-01-01",
  DefDumpFormat = "CSV",
  stjstr = "************************************************************\n",
  XLScols = as.vector(sapply(c("", as.vector(paste(sapply(c("", LETTERS[]), paste, LETTERS[], sep = "")))), paste, LETTERS[], sep = ""))
)



