#' @title load_and_format_filegroups_to_duckdb
#' @description
#' Read and format filegroups specified in parameters$files into duckdb
#' Teller file is loaded first, and other files are filtered according to years present in this file
#' Files are always loaded fresh into duckdb, and overwritten if they already exist. 
#' @param parameters list of parameters generated by get_cubeparameters()
load_and_format_filegroups_to_duckdb <- function(parameters){
  new_section_header("Laster og formatterer filgrupper")
  con <- parameters$duck
  tellerfile <- parameters$files$TELLER
  nonteller_files <- unique(grep(paste0("^", tellerfile, "$"), parameters$files, invert = T, value = T))
  
  load_filegroup_to_duckdb(con = con, filegroup = tellerfile, parameters = parameters)
  
  for (file in nonteller_files) {
    load_filegroup_to_duckdb(con = con, filegroup = file, parameters = parameters)
  }
  khtools::duckdb_clean(con = parameters$duck)
  khtools::msg("* Alle filer lest og formattert!")
}

#' @title load_filegroup_to_duckdb
#' @description Read and format single filegroup, save to duckdb
#' - fetch file information and other metadata
#' - finds original filegroup (if filefilter, this may be another file)
#' - generates ALDER and AAR filters (+tabfilter if tellerfile, lksfilter if population file)
#' - selects relevant columns and read file
#' - filters out irrelevant levels of dimension columns (KJONN, UTDANN, INNVAND, LANDBAK)
#' 
#' - harmonize GEO codes 
#' - FILFILTRE operations
#' - Special functions (add leadyear for BEFVEKST)
#' @return formatted filegroup in duckdb
#' @param con duckdb-connection
#' @param filegroup filegroup to load
#' @param parameters list of parameters generated by get_cubeparameters()
#' @noRd
load_filegroup_to_duckdb <- function(con, filegroup, parameters){
  khtools::duckdb_drop_tables(con = con, tables = filegroup)
  
  # Hent info
  fileinfo <- parameters$fileinformation[[filegroup]]
  filefilter <- parameters$FILFILTRE[tolower(FILVERSJON) == tolower(filegroup)]
  orgfile <- if(nrow(filefilter) > 0){ filefilter$ORGFIL } else { filegroup}
  isteller <- filegroup == parameters$files[["TELLER"]]
  isbef <- grepl("^BEF_GKny$", orgfile, ignore.case = TRUE)
  islks <- "V" %in% unlist(strsplit(parameters$CUBEinformation$GEOniv, ","))
  
  orgfilepath <- file.path(getOption("khfunctions.root"), getOption("khfunctions.fgdir"), getOption("khfunctions.fg.ny"), paste0(orgfile, ".parquet"))
  if(!file.exists(orgfilepath)) stop("Finner ikke filgruppe: ", orgfile, " i STABLAORG/R/NYESTE.")
  allcols <- DBI::dbGetQuery(con, sprintf("DESCRIBE SELECT * FROM read_parquet(%s)", khtools::sql_quote_s(con, orgfilepath)))$column_name
  
  tabfilter <- set_filter_tab_sql(isteller, cubeinformation = parameters$CUBEinformation)
  alderfilter <- set_filter_age_sql(con = con, parameters = parameters)
  yearfilter <- set_filter_year_sql(con = con, parameters = parameters)
  lksfilter <- set_filter_lks_sql(isbef = isbef, islks = islks, allcols = allcols)
  filter <- paste0(c(tabfilter, alderfilter, yearfilter, lksfilter), collapse = " AND ")
  readcols <- identify_readcols(allcols = allcols, bef = isbef, parameters = parameters)
  
  if(length(filter) == 0){
    khtools::msg("* Leser inn filgruppe", filegroup, "til duckdb")
  } else {
    khtools::msg("* Leser inn filgruppe", filegroup, "til duckdb med filter", filter)
  }
  read_filegroup_duckdb(con = con, tablename = filegroup, filepath = orgfilepath, filter = filter, readcols = readcols)
  
  do_filter_KUIL_duckdb(con = con, filegroup = filegroup, cubeinformation = parameters$CUBEinformation)

  ff <- get_filefilterconds(filefilter = filefilter, fileinfo = fileinfo, parameters = parameters)
  # if(!is.null(ff$nyekolkolprerad)){ #   # Bare brukt i sysvak, og flyttet til pre_fglagring, så denne er foreløpig inaktivert # }
  
  if(!is.null(ff$kollapsdel)){
    do_filfiltre_kollapsdeler_duckdb(con = con, filegroup = filegroup, parts = ff$kollapsdel, parameters = parameters)
  }
  
  if(!is.null(ff$Filter) && length(ff$Filter) > 0){
    prefilterdesign <- find_filedesign(file = NULL, filename = filegroup, parameters = parameters)
    redesign_filter <- find_redesign(orgdesign = prefilterdesign, targetdesign = list(Parts = ff$Filter), parameters = parameters)
    filter_and_recode_table_duckdb(con = con, tablename = filegroup, redesign = redesign_filter, parameters = parameters)
  }
  
  do_harmonize_geo_duckdb(con = con, tablename = filegroup, vals = fileinfo$vals)
  
  if(ff$rect){
    do_rectangularize_filfiltre_duckdb(con = con, tablename = filegroup, vals = fileinfo$vals, parameters = parameters)
  }
  
  if(!is.null(ff$nyekolrad)){
    khtools::msg(sprintf("\n** Henter data inn i R for å gjøre FILFILTRE::NYEKOL_RAD for %s, da denne funksjonen ikke er skrevet til sql enda", filegroup))
    dt <- khtools::duckdb_fetch_table(con, filegroup)
    compute_new_value_from_row_sum(dt = dt, formulas = filefilter$NYEKOL_RAD, fileinfo = fileinfo, parameters = parameters)
    khtools::duckdb_write_and_replace_table_from_R(con = con, tablename = filegroup, data = dt)
  }
  
  if(!is.null(ff$ffrsynt)){
    do_special_handling(name = "FF_RSYNT1", dt = NULL, dt_name = "Filgruppe", code = ff$ffrsynt, 
                        parameters = parameters, duck = TRUE, tablename = filegroup)
  }
  
  # Spesialfunksjoner
  if(filegroup == "BEFVEKST") add_leadyear_befvekst(con = con, tablename = filegroup)
  khtools::msg("\n* Filgruppe", filegroup, "lest og formattert\n")
}

# Innlesing og filtrering ----

#' @title set_filter_tab_sql
#' @description generate filter on TAB-columns, only applicable to tellerfile
#' @param isteller T/F is this tellerfile?
#' @param cubeinformation ACCESS::KUBER (from parameters)
#' @noRd
set_filter_tab_sql <- function(isteller, cubeinformation){
  
  if(!isteller) return(NULL)
  
  tabconds <- character()
  for(tab in names(cubeinformation)[grepl("^TAB\\d+$", names(cubeinformation))]){
    istab <- is_not_empty(cubeinformation[[tab]])
    if(!istab) next
    tab0 <- paste0(tab, "_0")
    istab0 <- is_not_empty(cubeinformation[[tab0]])
    tablist <- if(istab0) cubeinformation[[tab0]] else cubeinformation[[tab]]
    isminus <- grepl("^-\\[", tablist)
    tablist <- gsub("^-\\[(.*)\\]$", "\\1", tablist)
    vals <- trimws(strsplit(tablist, ",", fixed = TRUE)[[1]])
    vals_sql <- paste0("'", vals, "'", collapse = ", ")
    tabcond <- paste0(tab, " IN (", vals_sql, ")")
    if(isminus) tabcond <- paste0(tab, " NOT IN (", vals_sql, ")") 
    tabconds <- c(tabconds, tabcond)
  }
  
  if(length(tabconds) == 0) return(NULL)
  
  return(paste(tabconds, collapse = " AND "))
}

#' @title set_filter_age_sql
#' @description generate filter on age, based on ACCESS::KUBER::ALDER, or from tellerfile
#' @param con duckdb-connection
#' @param parameters global parameters
#' @noRd
set_filter_age_sql <- function(con, parameters){
  isalder <- is_not_empty(parameters$CUBEinformation$ALDER)
  if(!isalder){
    tellerfile <- parameters$files[["TELLER"]]
    isduck <- khtools::duckdb_table_exists(con = con, tablename = tellerfile)
    if(!isduck) return(NULL)
    if(isduck && all(c("ALDERl", "ALDERh") %in% khtools::duckdb_get_cols(con, tellerfile))){
      warning(
        "ACCESS::KUBER::ALDER er tom. Bruker aldersspenn fra tellerfil.",
        "Vurder å sette ALDER='ALLE' eksplisitt, eller angi konkrete aldersgrupper ",
        "for å sikre ønsket avgrensning."
      )
      a <- DBI::dbGetQuery(con, paste0("SELECT MIN(ALDERl) as min, MAX(ALDERh) as max FROM ", 
                                       khtools::sql_quote_I(con, tellerfile)))
      amin <- a$min
      amax <- a$max
    } else {
      return(NULL)
    }
  } else {
    accessalder <- unlist(strsplit(parameters$CUBEinformation$ALDER, ","))
    accessalder <- trimws(accessalder)
    if(any(toupper(accessalder) == "ALLE")) return(NULL)
    isvalid <- grepl("^([0-9]+)?(_([0-9]+)?)?$", accessalder)
    if(!all(isvalid)){
      stop("Feil i ACCESS::KUBER::ALDER. ",
        "Gyldige verdier er tom celle, 'ALLE' eller aldersgrupper på formen X_Y, X_, _Y.")
    }
    
    aldersplit <- data.table::tstrsplit(accessalder, "_")
    for(i in seq_along(aldersplit)) aldersplit[[i]][aldersplit[[i]] == ""] <- NA_character_

    amin <- ifelse(sum(is.na(aldersplit[[1]])) == 0,
                   min(as.integer(aldersplit[[1]])),
                   getOption("khfunctions.amin"))
    amax <- ifelse(length(aldersplit) > 1 && sum(is.na(aldersplit[[2]])) == 0, 
                   max(as.integer(aldersplit[[2]])),
                   getOption("khfunctions.amax"))
  }
  
  if(is.na(amin) || is.na(amax)) stop("Feil i aldersfiltreringen, som leser fra ACCESS::KUBER::ALDER. Denne må være tom, 'ALLE', eller angi aldersgrupper separert med komma (X_Y, X_Y, X_Y).")
  if(amin == getOption("khfunctions.amin") && amax == getOption("khfunctions.amax")) return(NULL)
  return(paste0("ALDERl >= ", amin, " AND ALDERh <= ", amax))
}

#' @title set_filter_year_sql
#' @description generate filter for which years to read, baser on ACCESS::KUBER::AAR_START, or from tellerfile
#' @param con duckdb-connection
#' @param parameters global parameters
#' @noRd
set_filter_year_sql <- function(con, parameters){
  tellerfile <- parameters$files[["TELLER"]]
  aarstart <- min_teller_aar <- parameters$CUBEinformation$AAR_START
  isduck <- khtools::duckdb_table_exists(con = con, tablename = tellerfile)
  if(isduck && "AARl" %in% khtools::duckdb_get_cols(con, tellerfile)){
    min_teller_aar <- DBI::dbGetQuery(con, paste0("SELECT MIN(AARl) FROM ", 
                                                  khtools::sql_quote_I(con, tellerfile)))[[1]]
  }
  
  min_aar <- max(aarstart, min_teller_aar, na.rm = TRUE)
  if(min_aar == 0){
    return(NULL)
    } else {
    return(paste0("AARl >= ", min_aar))
  }
}

#' @title set_filter_lks_sql
#' @description Special filter for population file, should GEOniv == "V" (80% of the file) be read or not
#' @param isbef T/F is the file population
#' @param islks T/F should lsk be read
#' @param allcols list of all columns in file
#' @noRd
set_filter_lks_sql <- function(isbef, islks, allcols){
  if(!isbef) return(NULL)
  if(islks) return(NULL)
  
  if("lks" %in% allcols){
    return("lks = 0")
  } else {
    return("CAST(GEO AS BIGINT) <= 999999")
  }
}

#' @title identify_readcols
#' @description selects which columns to read from filegroup
#' @noRd
identify_readcols <- function(allcols, bef = FALSE,  parameters){
  
  if(!bef){
    cols <- setdiff(allcols, c("KOBLID", "ROW", "FYLKE"))
  } else {
    befcols <- unique(grep("^BEF|^mBEF", unlist(parameters$TNPinformation[c("TELLERKOL", "NEVNERKOL")],
                                                use.names = FALSE),value = TRUE))
    befcols <- paste0(rep(befcols, each = 3), c("", ".f", ".a"))
    cols <- c(grep(paste0("^",getOption("khfunctions.standarddimensions"),collapse = "|"),allcols,value = TRUE),
              intersect(allcols, befcols))
  }
  return(cols)
}

#' @title do_filter_KUIL_duckdb
#' @description filters dimensions KJONN, UTDANN, INNVAND, LANDBAk
#' Use information in ACCESS to identify levels to keep, and discard unneeded rows 
#' (if all needed levels are present and not have to be aggregated from sublevels)
#' @noRd
do_filter_KUIL_duckdb <- function(con, filegroup, cubeinformation){
  tab_sql <- khtools::sql_quote_I(con, filegroup)
  allcols <- khtools::duckdb_get_cols(con, filegroup)
  filters <- character()
  filtercols <- character()
  for(dim in c("KJONN", "UTDANN", "INNVKAT", "LANDBAK")){
    if(!dim %in% allcols) next
    keep <- trimws(strsplit(cubeinformation[[dim]], ",", fixed = TRUE)[[1]])
    exist <- DBI::dbGetQuery(con, sprintf("SELECT DISTINCT %s FROM %s", 
                             khtools::sql_quote_I(con, dim), tab_sql))[[1]]
    
   
    if(all(keep %in% exist) && any(!exist %in% keep)){
      keep_sql <- paste0("'",keep,"'",collapse = ", ")
      filters <- c(filters,
                   sprintf("%s IN (%s)",
                           khtools::sql_quote_I(con, dim),keep_sql))
      filtercols <- c(filtercols, dim)
    }
  }
  
  if(length(filters) == 0) return(invisible(NULL))
  
  sql <- sprintf(
    "SELECT * FROM %s WHERE %s",
    tab_sql, paste(filters, collapse = " AND "))
  
  khtools::msg(sprintf("** Filtrerer filen på %s:\n- %s", 
                                paste(filtercols, collapse = ", "), 
                                paste(filters, collapse = "\n- ")))
  
  n_before <- DBI::dbGetQuery(con, sprintf("SELECT COUNT(*) AS N FROM %s", tab_sql))$N
  khtools::duckdb_create_and_replace_table(con, target = filegroup, select_sql = sql)
  n_after <- DBI::dbGetQuery(con, sprintf("SELECT COUNT(*) AS N FROM %s", tab_sql))$N
  khtools::msg(sprintf("-- %s -> %s rader", n_before, n_after))
  invisible(NULL)
}

#' @title read_filegroup_duckdb
#' @description Reads the file with preformatted filter and column selection
#' @param con duckdb-connection
#' @param tablename name of file in duckdb (same as filegroup name)
#' @param filepath path to original file
#' @param filter preformatted filter
#' @param readcols vector of columns to read
#' @noRd
read_filegroup_duckdb <- function(con, tablename, filepath, filter = NULL, readcols){
  schema <- data.table::setDT(DBI::dbGetQuery(con, sprintf("DESCRIBE SELECT * FROM read_parquet(%s)", khtools::sql_quote_s(con, filepath))))
  integer_cols <- intersect(c("AARl", "AARh", "ALDERl", "ALDERh", "KJONN", "UTDANN", "LANDBAK", "INNVKAT"), readcols)
  
  needs_cast <- schema[column_name %in% integer_cols & !toupper(column_type) %in% c("INTEGER", "INT", "BIGINT", "SMALLINT", "TINYINT")]$column_name
  
  select_cols <- vapply(readcols,
    function(col){
      col_sql <- khtools::sql_quote_I(con, col)
      if(col %in% needs_cast){
        sprintf("TRY_CAST(%s AS INTEGER) AS %s", col_sql, col_sql)
      } else {
        col_sql
      }
  }, character(1))
  
  tab_sql <- as.character(khtools::sql_quote_I(con, tablename))
  cols_sql <- paste(select_cols, collapse = ", ")
  
  where_sql <- if(is_not_empty(filter)) {
    sprintf(" WHERE %s", filter)
    } else { 
      ""
    }
  
  sql <- sprintf(
    "CREATE TABLE %s AS SELECT %s FROM read_parquet(%s)%s",
    tab_sql, cols_sql, khtools::sql_quote_s(con, filepath), where_sql)
  
  khtools::duckdb_drop_tables(con, tablename)
  invisible(DBI::dbExecute(con, sql))
  invisible(NULL)
}

# FILFILTRE ----
#' @title get_filefilterconds
#' @description henter info fra FILFILTRE
#' @noRd
get_filefilterconds <- function(filefilter, fileinfo, parameters){
  out <- list("nyekolkolprerad" = NULL, 
              "kollapsdel" = NULL, 
              "Filter" = NULL, 
              "rect" = FALSE, 
              "nyekolrad" = NULL, 
              "ffrsynt" = NULL)
  
  if(nrow(filefilter) > 0){
    if(grepl("\\S", filefilter$NYEKOL_KOL_preRAD)) out[["nyekolkolprerad"]] <- filefilter$NYEKOL_KOL_preRAD
    if(grepl("\\S", filefilter$KOLLAPSdeler)) out[["kollapsdel"]] <- filefilter$KOLLAPSdeler
    out[["Filter"]] <- set_recode_filter_filfiltre(fileinfo = fileinfo, filefilter = filefilter, parameters = parameters)
    out[["rect"]] <- filefilter$REKTISER == 1
    if(grepl("\\S", filefilter$NYEKOL_RAD)) out[["nyekolrad"]] <- filefilter$NYEKOL_RAD
    if(grepl("\\S", filefilter$FF_RSYNT1)) out[["ffrsynt"]] <- filefilter$FF_RSYNT1
  }
  
  return(out)
}

#' @title set_recode_filter_filfiltre
#' @description 
#' Uses information from FILFILTRE-columns GEONIV, ALDER, KJONN, UTDANN, LANDBAK, INNVKAT to further filter
#' a file version. This reduces file size by removing rows which is not needed. 
#' Years < KUBER:: AAR_START is already filtered out, and is therefore not included here. 
#' @keywords internal
#' @noRd
set_recode_filter_filfiltre <- function(fileinfo, filefilter, parameters){
  filters <- filefilter
  filtercols <- names(filters)[names(filters) %in% grep("^AAR$|^TAB\\d{1}$", parameters$DefDesign$DelKolN, value = T, invert = T)]
  filtercols <- filtercols[sapply(filters[, ..filtercols], function(col) is_not_empty(col))]
  deler <- parameters$DefDesign$DelKolN
  deler <- names(deler)[deler %in% c(filtercols)]
  out <- list()
  
  for(del in deler){
    delkol <- parameters$DefDesign$DelKolN[del]
    delkolnames <- parameters$DefDesign$DelKols[[del]]
    delvalue <- unlist(strsplit(trimws(filters[[delkol]]), ","))
    delformat <- parameters$DefDesign$DelFormat[[del]]
    if(del == "A"){
      delvalue <- gsub("ALLE", paste0(fileinfo$amin, "_", fileinfo$amax), delvalue)
      delvalue <- gsub("^_(\\d+)", paste0(fileinfo$amin, "_\\1"), delvalue)
      delvalue <- gsub("(\\d+)_$", paste0("\\1_", fileinfo$amax), delvalue)
      delvalue <- gsub("^(\\d+)$", "\\1_\\1", delvalue)
      delvalue <- data.table::as.data.table(data.table::tstrsplit(delvalue, "_", type.convert = TRUE))
    } else {
      delvalue <- data.table::as.data.table(as.integer(delvalue))
    }
    out[[del]] <- data.table::setnames(delvalue, delkolnames)
  }
  return(out)
}


#' @title do_filfiltre_kollapsdeler_duckdb
#' @description Kollapser kolonner som angitt i filfiltre
#' @family duckdb
#' @noRd
do_filfiltre_kollapsdeler_duckdb <- function(con, filegroup, parts, parameters){
  
  parts <- trimws(strsplit(parts, ",", fixed = TRUE)[[1]])
  columns <- as.character(unlist(parameters$DefDesign$DelKolsF[parts]))
  totals <- as.character(unlist(parameters$TotalKoder[parts]))
  tab_sql <- as.character(khtools::sql_quote_I(con, filegroup))
  
  for(i in seq_along(columns)){
    
    exists_total <- DBI::dbGetQuery(con,
                                    sprintf("SELECT * FROM %s WHERE %s = '%s' LIMIT 1", 
                                            tab_sql, 
                                            khtools::sql_quote_I(con, columns[i]), 
                                            totals[i]))
    
    if(nrow(exists_total) > 0){
      stop(sprintf("FILFILTRE: Kan ikke kollapse '%s' – inneholder allerede totalverdi '%s'",
                   columns[i],
                   totals[i]))
      }
  }
  
  updatecols <- khtools::sql_quote_I(con, columns)
  updatetotals <- khtools::sql_quote_s(con, totals)
  
  set_sql <- sprintf("%s = %s", 
                     updatecols, updatetotals)
  sql <- sprintf("UPDATE %s SET %s", 
                 tab_sql, paste(set_sql, collapse = ", "))
  
  khtools::msg(sprintf("\nKollapser kolonnene %s", paste(updatecols, collapse = ", ")))
  
  n_before <- DBI::dbGetQuery(con, sprintf("SELECT COUNT(*) AS N FROM %s", tab_sql))$N
  invisible(DBI::dbExecute(con, sql))
  do_aggregate_file_duckdb(con = con, tablename = filegroup)
  n_after <- DBI::dbGetQuery(con, sprintf("SELECT COUNT(*) AS N FROM %s", tab_sql))$N
  khtools::msg(sprintf("- %s -> %s rader", n_before, n_after))
}

#' @title do_rectangularize_filfiltre_duckdb
#' @description Rektangulariserer filen dersom angitt i FILFILTRE
#' @family duckdb
#' @noRd
do_rectangularize_filfiltre_duckdb <- function(con, tablename, vals = list(), parameters){
  on.exit({
    tmp_design_tabs <- grep("^tmp_designgeo_", khtools::duckdb_get_tables(con = con), value = TRUE)
    khtools::duckdb_drop_tables(con, c("tmp_rectangularized", tmp_design_tabs))
    }, add = TRUE)
  
  khtools::msg("\n*** Rektangulariserer filfiltre")
  design <- find_filedesign(file = NULL, filename = tablename, parameters = parameters)
  year <- ifelse(is_empty(parameters$year), getOption("khfunctions.year"), parameters$year)
  rect_table <- "tmp_rectangularized"
  khtools::duckdb_drop_tables(con, rect_table)
  
  create_sql <- character()
  file_cols <- khtools::duckdb_get_cols(con, tablename)
  design_cols <- intersect(file_cols, names(design$Design))
  
  for(Gn in design$Part[["Gn"]][["GEOniv"]]){
    designgeo <- unique(design$Design[HAR == 1 & GEOniv == Gn, ..design_cols])
    design_table <- sprintf("tmp_designgeo_%s", Gn)
    
    khtools::duckdb_drop_tables(con, design_table)
    khtools::duckdb_write_table(con, design_table, designgeo)
    # DBI::dbWriteTable(con, design_table, designgeo, temporary = TRUE, overwrite = TRUE)
    
    create_sql <- c(create_sql, sprintf(
    "SELECT d.*, g.GEO FROM %s d
    CROSS JOIN (SELECT GEO FROM GeoKoder WHERE GEOniv = '%s' AND FRA <= %s AND TIL > %s) g",
    design_table, Gn, year, year))
  }
  
  rectangularize_sql <- sprintf("CREATE TEMP TABLE %s AS %s", rect_table, paste(create_sql, collapse = "\nUNION ALL\n"))
  
  invisible(DBI::dbExecute(con, rectangularize_sql))
  
  join_cols <- intersect(khtools::duckdb_get_cols(con, rect_table), khtools::duckdb_get_cols(con, tablename))
  join_cols_sql <- paste(khtools::sql_quote_I(con, join_cols), collapse = ", ")
  
  table_cols <- setdiff(khtools::duckdb_get_cols(con, tablename), join_cols)
  table_cols_sql <- paste(sprintf("f.%s", khtools::sql_quote_I(con, table_cols)),collapse = ",\n")
  
  merge_sql <- sprintf(
    "SELECT r.*, %s FROM tmp_rectangularized r LEFT JOIN %s f USING (%s)",
    table_cols_sql, khtools::sql_quote_I(con, tablename), join_cols_sql
  )
  
  n_before <- DBI::dbGetQuery(con, sprintf("SELECT COUNT(*) AS N FROM %s", khtools::sql_quote_I(con, tablename)))$N
  khtools::duckdb_create_and_replace_table(con, target = tablename, select_sql = merge_sql)
  n_after <- DBI::dbGetQuery(con, sprintf("SELECT COUNT(*) AS N FROM %s", khtools::sql_quote_I(con, tablename)))$N
  khtools::msg(sprintf("- %s -> %s rader", n_before, n_after))
  
  set_implicit_null_after_merge_duckdb(table = tablename, implicitnull_defs = vals, con = con)
  invisible(NULL)
}

# Spesialfunksjoner ----

#' @title add_leadyear_befvekst_duckdb
#' @description Adds lead year variables for filegroup BEFVEKST
#' @family duckdb
#' @keywords internal
#' @noRd
add_leadyear_befvekst <- function(con, tablename){
  tmp_table <- "tmp_leadyear_befvekst"
  on.exit(khtools::duckdb_drop_tables(con, tmp_table), add = TRUE)
  khtools::duckdb_drop_tables(con, tmp_table)
  
  khtools::msg("\n*** Legger til ledeår for å beregne befolkningsvekst")
  table_cols <- khtools::duckdb_get_cols(con, tablename)
  dims <- get_dimension_columns(table_cols)
  dims_sql <- khtools::sql_quote_I(con, dims)
  
  create_sql <- sprintf(
  "CREATE TEMP TABLE %s AS 
    SELECT * EXCLUDE (AARl, AARh), AARl - 1 AS AARl, AARh - 1 AS AARh
  FROM %s",
  khtools::sql_quote_I(con, tmp_table), 
  khtools::sql_quote_I(con, tablename))
  invisible(DBI::dbExecute(con, create_sql))
  
  dup_sql <- sprintf(
    "SELECT MAX(N) AS N 
    FROM (
      SELECT %s, COUNT(*) AS N 
      FROM %s GROUP BY %s
    ) count_table",
    paste(dims_sql, collapse = ", "),
    khtools::sql_quote_I(con, tmp_table),
    paste(dims_sql, collapse = ", ")
  )
  
  max_n <- DBI::dbGetQuery(con, dup_sql)$N
  if(is.na(max_n) || max_n != 1) stop("Data for ledeår er ikke unike (eller gir tom tabell) etter forskyving av AARl og AARh")
  
  join_sql <- paste(sprintf("t.%s = y.%s", dims_sql, dims_sql), collapse = "\n  AND ")
  
  merge_sql <- sprintf(
    'SELECT t.*, 
    y.BEF0101 AS Yp1_A_BEF0101, 
    y."BEF0101.f" AS "Yp1_A_BEF0101.f", 
    y."BEF0101.a" AS "Yp1_A_BEF0101.a"
    FROM %s t LEFT JOIN %s y ON %s',
    khtools::sql_quote_I(con, tablename), 
    khtools::sql_quote_I(con, tmp_table), 
    join_sql) 
  
  khtools::duckdb_create_and_replace_table(con, target = tablename, select_sql = merge_sql)
  invisible(NULL)
}


# Old version which is still needed some places ----
#' @title do_filter_columns
#' @description
#' Filters file according to filtering string, such as tabfilter generated by
#' @param file file to filter
#' @param filter filtering string
#' @noRd
do_filter_columns <- function(file, filter){
  file <- file[x, env = list(x = str2lang(filter))]
  return(file)
}

#' @title do_aggregate_file
#' @description Aggregates file
#' @param file file to aggregate
#' @param valsumbardef list of value column definitions. Not summable values are removed. 
#' @noRd
do_aggregate_file <- function(file, valsumbardef = list()){
  if(!is(file, "data.table")) data.table::setDT(file)
  tabcols <- get_dimension_columns(names(file))
  valcols <- get_value_columns(names(file))
  colorder <- tabcols 
  for(val in valcols){
    file[is.na(file[[val]]) | file[[val]] == 0, paste0(val, ".a") := 0]
    colorder <- c(colorder, paste0(val, c("", ".f", ".a")))
  }
  if(!identical(data.table::key(file), tabcols)) data.table::setkeyv(file, tabcols)
  
  g <- collapse::GRP(file, tabcols)
  aggfile <- collapse::add_vars(g[["groups"]],
                                collapse::fsum(collapse::get_vars(file, valcols), g = g),
                                collapse::fmax(collapse::get_vars(file, paste0(valcols, ".f")), g = g),
                                collapse::fsum(collapse::get_vars(file, paste0(valcols, ".a")), g = g))
  
  for(val in valcols){
    if(val %in% names(valsumbardef) && valsumbardef[[val]]$sumbar == 0){
      valA <- paste0(val, ".a")
      valF <- paste0(val, ".f")
      aggfile[aggfile[[valA]] > 1, c(val, valF) := list(NA, 2)]
    }
  }
  data.table::setcolorder(aggfile, colorder)
  return(aggfile)
}







# DEPRECATED ----
