#' @title load_and_format_files
#' @description
#' Loads filegroups as specified in parameters$files
#' Adds FileDesign to parameter list after loading files
#' Teller file is loaded first, and other files are filtered according to years present in this file
#' Files are always loaded fresh into BUFFER, and overwritten if they already exist. 
#' @param parameters list of parameters generated by get_cubeparameters()
#' @return updated parameter list after loading and formatting files
load_and_format_files <- function(parameters){
  cat("\n* Laster og formatterer filgrupper\n")
  if(!exists("BUFFER", envir = .GlobalEnv)) .GlobalEnv$BUFFER <- list()
  tabfilter_tellerfile <- set_filter_tab(cubeinformation = parameters$CUBEinformation)
  tellerfile <- parameters$files$TELLER
  if(tellerfile %in% names(.GlobalEnv$BUFFER)) BUFFER[[tellerfile]] <- NULL
  if(is_duckdb_file(con = parameters$duck, filename = tellerfile)) DBI::dbRemoveTable(parameters$duck, tellerfile)
  load_filegroup_to_buffer(filegroup = tellerfile, filter = tabfilter_tellerfile, parameters = parameters)
  
  nonteller_files <- unique(grep(paste0("^", tellerfile, "$"), parameters$files, invert = T, value = T))
  for (file in nonteller_files) {
    if(file %in% names(.GlobalEnv$BUFFER)) BUFFER[[file]] <- NULL
    if(is_duckdb_file(con = parameters$duck, filename = file)) DBI::dbRemoveTable(parameters$duck, file)
    load_filegroup_to_buffer(filegroup = file, filter = NULL, parameters = parameters)
  }
  do_clean_duckdb(parameters = parameters)

  parameters[["filedesign"]] <- get_filedesign(parameters = parameters)
  parameters[["PredFilter"]] <- set_predictionfilter(parameters = parameters)
  cat("\n* Alle filer lest og formattert")
  return(parameters)
}

#' @title load_filegroup_to_buffer
#' @description
#' Loads the file into BUFFER in .GlobalEnv
#' The file is filtered using TABfilter and geoharmonized. 
#' If filefilter is defined, the file is formatted accordingly
#' @noRd
load_filegroup_to_buffer <- function(filegroup, filter = NULL, parameters, duck = TRUE){
  filefilter <- parameters$FILFILTRE[tolower(FILVERSJON) == tolower(filegroup)]
  isfilefilter <- nrow(filefilter) > 0
  alderfilter <- set_filter_age(parameters = parameters)
  yearfilter <- set_filter_year(parameters = parameters)
  filter <- paste0(c(filter, alderfilter, yearfilter), collapse = " & ")
  isfilter <- is_not_empty(filter)
  fileinfo <- parameters$fileinformation[[filegroup]]
  orgfile <- ifelse(isfilefilter, filefilter$ORGFIL, filegroup)
  
  if(grepl("^BEF_GKny$", orgfile, ignore.case = TRUE)){
    FIL <- read_population_file(alderfilter = alderfilter, yearfilter = yearfilter, parameters = parameters)
  } else {
    FIL <- read_filegroup(filegroup = orgfile)
  }
  
  if(isfilter) FIL <- do_filter_columns(file = FIL, filter = filter)
  
  FIL <- do_filter_KUIL(dt = FIL, parameters = parameters)
  
  if(!isfilefilter){
    FIL <- do_harmonize_geo(file = FIL, vals = fileinfo$vals, rectangularize = FALSE, parameters = parameters)
  } else {
    iskollapsdel <- grepl("\\S", filefilter$KOLLAPSdeler)
    if(iskollapsdel) FIL <- do_filfiltre_kollapsdeler(file = FIL, parts = filefilter$KOLLAPSdeler, parameters = parameters)
    
    isnyekolkolprerad <- grepl("\\S", filefilter$NYEKOL_KOL_preRAD)
    if(isnyekolkolprerad) compute_new_value_from_formula(dt = FIL, formulas = filefilter$NYEKOL_KOL_preRAD, post_moving_average = FALSE)
    
    Filter <- set_recode_filter_filfiltre(fileinfo = fileinfo, filefilter = filefilter, parameters = parameters)
    if (length(Filter) > 0){
      prefilterdesign <- find_filedesign(FIL, parameters = parameters)
      redesign_filter <- find_redesign(orgdesign = prefilterdesign, targetdesign = list(Parts = Filter), parameters = parameters)
      FIL <- do_filter_and_recode_to_redesign(dt = FIL, redesign = redesign_filter, parameters = parameters)
    }
    
    isgeoharm <- filefilter$GEOHARM == 1
    if(isgeoharm){
      rectangularize <- ifelse(filefilter$REKTISER == 1, TRUE, FALSE)
      FIL <- do_harmonize_geo(file = FIL, vals = fileinfo$vals, rectangularize = rectangularize, parameters = parameters)
    }
    
    isnyekolrad <- grepl("\\S", filefilter$NYEKOL_RAD)
    if(isnyekolrad) compute_new_value_from_row_sum(dt = FIL, formulas = filefilter$NYEKOL_RAD, fileinfo = fileinfo, parameters = parameters)
    
    # isnykolsmerge <- grepl("\\S", filefilter$NYKOLSmerge)
    # if(isnykolsmerge){
    #   newcols <- eval(str2lang(filefilter$NYKOLSmerge))
    #   do_filfiltre_nykolsmerge(file = FIL, newcols = newcols)
    # }
      
    isffrsynt <- grepl("\\S", filefilter$FF_RSYNT1)
    if(isffrsynt) FIL <- do_special_handling(name = "FF_RSYNT1", dt = FIL, dt_name = "FIL", code = filefilter$FF_RSYNT1, parameters = parameters)
  }
  
  if(filegroup == "BEFVEKST") add_leadyear_befvekst(dt = FIL)
  dimorder <- intersect(getOption("khfunctions.standarddimensions_full"), names(FIL))
  data.table::setcolorder(FIL, dimorder)

  if(duck){
    cat("\n*** Skriver til duckdb...\n")
    DBI::dbWriteTable(parameters$duck, name = filegroup, value = FIL, overwrite = TRUE)
  } else {
    cat("\n*** Skriver til lokalt minne...")
    .GlobalEnv$BUFFER[[filegroup]] <- FIL
  }
  invisible(gc())
}

#' @title do_filter_columns
#' @description
#' Filters file according to filtering string, such as tabfilter generated by
#' @param file file to filter
#' @param filter filtering string
#' @noRd
do_filter_columns <- function(file, filter){
  file <- file[x, env = list(x = str2lang(filter))]
  return(file)
}

#' @title set_filter_tab
#' @description
#' Creates a filtering string based on the TABX and TABX_0 columns in table KUBER in ACCESS
#' If TABX_0 is provided, this is used for initial filtering of the filegroup, as these categories are needed during the data processing.
#' TABX is always used for final filtering of the cube.
#' @param cubeinformation information from table KUBER in ACCESS
#' @noRd
set_filter_tab <- function(cubeinformation){
  TabConds <- character()
  for (tab in names(cubeinformation)[grepl("^TAB\\d+$", names(cubeinformation))]){
    istab <- !is.na(cubeinformation[[tab]]) && cubeinformation[[tab]] != ""
    if (istab) {
      tab0 <- paste0(tab, "_0")
      istab0 <- !is.null(cubeinformation[[tab0]]) && !is.na(cubeinformation[[tab0]]) && cubeinformation[[tab0]] != ""
      tablist <- cubeinformation[[tab]]
      if(istab0) tablist <- cubeinformation[[tab0]]
      isminus <- grepl("^-\\[", tablist)
      tablist <- gsub("^-\\[(.*)\\]$", "\\1", tablist)
      tablist <- paste0("\"", gsub(",", "\",\"", tablist), "\"")
      tabcond <- paste0("(", tab, " %in% c(", tablist, "))")
      if (isminus) tabcond <- paste0("!", tabcond)
      TabConds <- c(TabConds, tabcond)
    }
  } 
  tabfilter <- paste0(TabConds, collapse = " & ")
  if(tabfilter == "") tabfilter <- NULL
  return(tabfilter)
}

#' @title set_filter_year
#' @description
#' Sets age filter according to age groups set in ACCESS::KUBER, 
#' @noRd
set_filter_age <- function(parameters){
  isalder <- is_not_empty(parameters$CUBEinformation$ALDER)
  if(!isalder){
    tellerfile <- parameters$files[["TELLER"]]
    isbuffer <- tellerfile %in% names(.GlobalEnv$BUFFER)
    isduck <- is_duckdb_file(con = parameters$duck, filename = tellerfile)
    if(!isbuffer && !isduck) return(NULL)
    if(isduck && all(c("ALDERl", "ALDERh") %in% DBI::dbListFields(parameters$duck, tellerfile))){
      a <- DBI::dbGetQuery(parameters$duck, paste0("SELECT MIN(ALDERl) as min, MAX(ALDERh) as max FROM ", tellerfile))
      amin <- a$min
      amax <- a$max
    } else if(isbuffer && all(c("ALDERl", "ALDERh") %in% names(.GlobalEnv$BUFFER[[tellerfile]]))){
      amin <- collapse::fmin(.GlobalEnv$BUFFER[[tellerfile]][["ALDERl"]])
      amax <- collapse::fmax(.GlobalEnv$BUFFER[[tellerfile]][["ALDERh"]])
    } else {
      return(NULL)
    }
  } else {
    accessalder <- unlist(strsplit(parameters$CUBEinformation$ALDER, ","))
    if(any(grepl("[^[:digit:]_]", accessalder))) return(NULL)
  
    aldersplit <- data.table::tstrsplit(accessalder, "_")
    amin <- ifelse(sum(is.na(aldersplit[[1]])) == 0,
                   min(as.numeric(aldersplit[[1]])),
                   getOption("khfunctions.amin"))
    amax <- ifelse(length(aldersplit) > 1 && sum(is.na(aldersplit[[2]])) == 0, 
                   max(as.numeric(aldersplit[[2]])),
                   getOption("khfunctions.amax"))
  }
  
  if(is.na(amin) | is.na(amax)) stop("Feil i aldersfiltreringen, som leser fra ACCESS::KUBER::ALDER. Denne må være tom, 'ALLE', eller angi aldersgrupper separert med komma (X_Y, X_Y, X_Y).")
  if(amin == getOption("khfunctions.amin") && amax == getOption("khfunctions.amax")) return(NULL)
  return(paste0("ALDERl >= ", amin, " & ALDERh <= ", amax))
}

#' @title set_filter_year
#' @description Filters filegroups to remove years prior to AAR_START in ACCESS::KUBER
#' If tellerfile is already loaded, use the maximum of AAR_START and min(tellerfile[[AARl]]) as filter
#' @keywords internal
#' @noRd
set_filter_year <- function(parameters){
  tellerfile <- parameters$files[["TELLER"]]
  aarstart <- min_teller_aar <- parameters$CUBEinformation$AAR_START
  isbuffer <- tellerfile %in% names(.GlobalEnv$BUFFER)
  isduck <- is_duckdb_file(con = parameters$duck, filename = tellerfile)
  if(isduck && "AARl" %in% DBI::dbListFields(parameters$duck, tellerfile)){
    min_teller_aar <- DBI::dbGetQuery(parameters$duck, paste0("SELECT MIN(AARl) FROM ", tellerfile))[[1]]
  } else if(isbuffer && "AARl" %in% names(.GlobalEnv$BUFFER[[tellerfile]])){
    min_teller_aar <- collapse::fmin(.GlobalEnv$BUFFER[[tellerfile]][["AARl"]])
  }
  if(aarstart == 0) return(invisible(NULL))
  return(paste0("AARl >= ", pmax(aarstart, min_teller_aar)))
}

#' @title do_filter_KUIL
#' @description 
#' Filters out only needed categories of KJONN, UTDANN, INNVKAT, LANDBAK
#' If only total is needed, and total already exist, only keep this value.
#' Reduces the size of input files before further processing. 
#' @keywords internal
#' @noRd
do_filter_KUIL <- function(dt, parameters){
  for(dim in c("KJONN", "UTDANN", "INNVKAT", "LANDBAK")){
    keep <- trimws(strsplit(parameters$CUBEinformation[[dim]], split = ",")[[1]])
    exist <- collapse::funique(dt[[dim]])
    if(all(keep %in% exist) && any(exist %notin% keep)){
      dt <- dt[dt[[dim]] %in% keep]
    }
  }
  return(dt)
}

#' @keywords internal
#' @noRd
read_population_file <- function(alderfilter = NULL, yearfilter = NULL, parameters){
  root <- file.path(getOption("khfunctions.root"), getOption("khfunctions.fgdir"), getOption("khfunctions.fg.ny"))
  isalderfilter <- is_not_empty(alderfilter)
  isyearfilter <- is_not_empty(yearfilter)
  islks <- "V" %in% unlist(strsplit(parameters$CUBEinformation$GEOniv, ","))
  befcols <- grep("^BEF|^mBEF", unlist(parameters$TNPinformation[c("TELLERKOL", "NEVNERKOL")], use.names = F), value = T)
  befcols <- paste0(rep(befcols, each = 3), c("", ".f", ".a"))
  
  use_dataset <- isalderfilter || isyearfilter || !islks
  if(!use_dataset){
    cat("\n** Leser inn full befolkningsfil (ingen filter angitt for ALDER, AAR eller GEOniv).....")
    file <- arrow::open_dataset(file.path(root, "BEF_GKny.parquet"))
    readcols <- c(grep(paste0("^", getOption("khfunctions.standarddimensions"), collapse = "|"), names(file), value = T), befcols)
    dt <- file |> 
      dplyr::select(dplyr::all_of(readcols)) |> 
      dplyr::collect() |> 
      data.table::setDT()
    return(dt)
  }
  
  folder <- ifelse(isalderfilter, getOption("khfunctions.pop_alderaargeo"), getOption("khfunctions.pop_aargeo"))
  
  if(isalderfilter){
    available_age_groups <- gsub("alder=", "", list.dirs(file.path(root, folder), full.names = F, recursive = F))
    alderfilter <- translate_age_filter(alderfilter = alderfilter, all = available_age_groups)
  }
  
  file <- arrow::open_dataset(file.path(root, folder))
  
  geofilter <- ifelse(islks, "lks %in% c(0, 1)", "lks == 0")
  completefilter <- paste(c(alderfilter, yearfilter, geofilter), collapse = " & ")
  readcols <- c(grep(paste0("^", getOption("khfunctions.standarddimensions"), collapse = "|"), names(file), value = T), befcols)
  cat(paste0("\n** Leser inn befolkningsfil med filter: ", completefilter, "....."))
  dt <- file |> 
    dplyr::filter(!!rlang::parse_expr(completefilter)) |> 
    dplyr::select(dplyr::all_of(readcols)) |> 
    dplyr::collect() |> 
    data.table::setDT()
  cat("Ferdig")
  return(dt)
}

#' @keywords internal
#' @noRd
translate_age_filter <- function(alderfilter, all){
  aldermin <- as.integer(sub("ALDERl >= (\\d+) & .*", "\\1", alderfilter))
  aldermax <- as.integer(sub(".* ALDERh <= (\\d+)", "\\1", alderfilter))
  tab <- data.table::data.table(all = all)
  tab[, c("l", "h") := data.table::tstrsplit(all, "_")][, included := 1L]
  tab[as.numeric(h) < aldermin | as.numeric(l) > aldermax, included := 0L]
  needed <- tab[included == 1, all]
  filterstr <- paste0("alder %in% c(", paste0(shQuote(needed), collapse = ", "), ")")
  return(filterstr)
}

#' @title read_filegroup
#' @description Reads original filegroup. Will always read from "PARQUET" folder first. 
#' If filegroup does not exist it will look in "NYESTE" to read the .rds file, and throw an error if not found.
#' Can be used alone to read filegroups from PARQUET/NYESTE by name. 
#' @returns data.table
#' @export
read_filegroup <- function(filegroup){
  file <- file.path(getOption("khfunctions.root"), getOption("khfunctions.fgdir"), getOption("khfunctions.fg.ny"), paste0(filegroup, ".parquet"))
  if(file.exists(file)){
    cat(paste0("\n** Leser inn fil: ", file, "....."))
    dt <- arrow::open_dataset(file)
    readcols <- grep("^KOBLID$|^ROW$", names(dt), value = TRUE, invert = TRUE)
    dt <- dt |> 
      dplyr::select(all_of(readcols)) |> 
      dplyr::collect() |> 
      data.table::setDT()
  } else {
    file <- file.path(getOption("khfunctions.root"), getOption("khfunctions.fgdir"), getOption("khfunctions.fg.ny"), paste0(filegroup, ".rds"))
    if(!file.exists(file)) stop("Finner ikke filgruppe: ", filegroup, " i STABLAORG/R/NYESTE! Filgruppen må kjøres først.")
    cat("\n** Leser inn fil: ", file, " ..... ")
    dt <- collapse::qDT(readRDS(file))
    delcols <- names(dt)[names(dt) %in% c("KOBLID", "ROW")]
    dt[, (delcols) := NULL]
  }
  set_integer_columns(dt = dt)
  return(dt)
}

#' @title fetch_filegroup_from_buffer
#' @description
#' fetches filegroup already loaded into buffer. 
#' @keywords internal
#' @noRd
fetch_filegroup_from_buffer <- function(filegroup){
  if(exists("BUFFER", envir = .GlobalEnv) && filegroup %in% names(.GlobalEnv$BUFFER)){
    cat("\n** Henter FIL", filegroup, "fra BUFFER")
    return(data.table::copy(.GlobalEnv$BUFFER[[filegroup]]))
  }
  stop("Filgruppe ", filegroup, " ikke funnet i BUFFER")
}

fetch_filegroup_from_duckdb <- function(filegroup, parameters){
  if(is_duckdb_file(con = parameters$duck, filename = filegroup)){
    cat("\n** Henter FIL", filegroup, "fra duckdb")
    return(data.table::setDT(DBI::dbReadTable(parameters$duck, filegroup)))
  }
  stop("Filgruppe ", filegroup, " ikke funnet i duckdb")
}

#' @title do_aggregate_file
#' @description Aggregates file
#' @param file file to aggregate
#' @param valsumbardef list of value column definitions. Not summable values are removed. 
#' @noRd
do_aggregate_file <- function(file, valsumbardef = list()){
  if(!is(file, "data.table")) data.table::setDT(file)
  tabcols <- get_dimension_columns(names(file))
  valcols <- get_value_columns(names(file))
  colorder <- tabcols 
  for(val in valcols){
    file[is.na(file[[val]]) | file[[val]] == 0, paste0(val, ".a") := 0]
    colorder <- c(colorder, paste0(val, c("", ".f", ".a")))
  }
  if(!identical(data.table::key(file), tabcols)) data.table::setkeyv(file, tabcols)
  
  g <- collapse::GRP(file, tabcols)
  aggfile <- collapse::add_vars(g[["groups"]],
                                collapse::fsum(collapse::get_vars(file, valcols), g = g),
                                collapse::fmax(collapse::get_vars(file, paste0(valcols, ".f")), g = g),
                                collapse::fsum(collapse::get_vars(file, paste0(valcols, ".a")), g = g))
  
  for(val in valcols){
    if(val %in% names(valsumbardef) && valsumbardef[[val]]$sumbar == 0){
      valA <- paste0(val, ".a")
      valF <- paste0(val, ".f")
      aggfile[file[[valA]] > 1, c(val, valF) := list(NA, 2)]
    }
  }
  data.table::setcolorder(aggfile, colorder)
  return(aggfile)
}

#' @title do_filfiltre_kollapsdeler
#' @description 
#' collapses file according to the KOLLAPSdeler column in table FILFILTRE
#' The selected columns are set to the total value, and all non-dimension values are aggregated usin fsum
#' NB! If the column already contains the total value, this will generate an error as the total will be included in the sum. 
#' @noRd
do_filfiltre_kollapsdeler <- function(file, parts, parameters){
  tabcols <- get_dimension_columns(names(file))
  parts <- unlist(strsplit(parts, ","))
  totals <- parameters$TotalKoder[parts]
  columns <- as.character(parameters$DefDesign$DelKolsF[parts])
  for(i in seq_along(parts)){
    if(totals[[i]] %in% collapse::funique(file[[columns[i]]])){
      stop(sprintf("FILFILTRE: Kan ikke kollapse '%s' – inneholder allerede totalverdi '%s'", columns[i], totals[[i]]))
    }
  }
  file[, (columns) := totals]
  cat(paste0("\n*** Kollapser kolonnene: ", paste0(columns, collapse = ", ")))
  file <- file[, collapse::fsum(collapse::gby(.SD, tabcols))]
  return(file)
}  

# do_filfiltre_nykolsmerge <- function(file, newcols){
#   commoncols <- intersect(get_dimension_columns(names(newcols)), get_dimension_columns(names(file)))
#   newcolnames <- setdiff(names(newcols), commoncols)
#   newcolvals <- newcols[file, on = commoncols, ..newcolnames]
#   data.table::set(file, j = newcolnames, value = newcolvals)
# }

#' @title set_recode_filter_filfiltre
#' @description 
#' Uses information from FILFILTRE-columns GEONIV, ALDER, KJONN, UTDANN, LANDBAK, INNVKAT to further filter
#' a file version. This reduces file size by removing rows which is not needed. 
#' Years < KUBER:: AAR_START is already filtered out, and is therefore not included here. 
#' @keywords internal
#' @noRd
set_recode_filter_filfiltre <- function(fileinfo, filefilter, parameters){
  filters <- filefilter
  filtercols <- names(filters)[names(filters) %in% grep("^AAR$|^TAB\\d{1}$", parameters$DefDesign$DelKolN, value = T, invert = T)]
  filtercols <- filtercols[sapply(filters[, ..filtercols], function(col) is_not_empty(col))]
  deler <- parameters$DefDesign$DelKolN
  deler <- names(deler)[deler %in% c(filtercols)]
  out <- list()
  
  for(del in deler){
    delkol <- parameters$DefDesign$DelKolN[del]
    delkolnames <- parameters$DefDesign$DelKols[[del]]
    delvalue <- unlist(strsplit(trimws(filters[[delkol]]), ","))
    delformat <- parameters$DefDesign$DelFormat[[del]]
    if(del == "A"){
      delvalue <- gsub("ALLE", paste0(fileinfo$amin, "_", fileinfo$amax), delvalue)
      delvalue <- gsub("^_(\\d+)", paste0(fileinfo$amin, "_\\1"), delvalue)
      delvalue <- gsub("(\\d+)_$", paste0("\\1_", fileinfo$amax), delvalue)
      delvalue <- gsub("^(\\d+)$", "\\1_\\1", delvalue)
      delvalue <- data.table::as.data.table(data.table::tstrsplit(delvalue, "_", type.convert = TRUE))
    } else {
      delvalue <- data.table::as.data.table(as.integer(delvalue))
    }
    out[[del]] <- data.table::setnames(delvalue, delkolnames)
  }
  return(out)
}

#' @keywords internal
#' @noRd
set_integer_columns <- function(dt){
  integers <- names(dt)[grep("^(AAR(l|h)|ALDER(l|h)|KJONN|UTDANN|LANDBAK|INNVKAT)$", names(dt))]
  non_int_cols <- names(dt)[!sapply(dt, is.integer)]
  to_integer <- intersect(non_int_cols, integers)
  dt[, names(.SD) := lapply(.SD, as.integer), .SDcols = to_integer]
}

#' @title add_leadyear_befvekst
#' @description
#' Adds lead years for filegroup BEFVEKST
#' @keywords internal
#' @noRD
add_leadyear_befvekst <- function(dt){
  d <- data.table::copy(dt)
  data.table::set(d, j = c("AARl", "AARh"), 
                  value = list(d[["AARl"]] - 1, d[["AARh"]] - 1))
  tabcols <- get_dimension_columns(names(d))
  if(!d[, max(.N), by = tabcols][, max(V1)] == 1){
    stop("")
  }
  prefix <- "Yp1_A_"
  oldval_names <- paste0("BEF0101", c("", ".f", ".a"))
  newval_names <- paste0(prefix, oldval_names)
  data.table::setnames(d, old = oldval_names, new = newval_names)
  
  newval_vals <- d[dt, on = tabcols, ..newval_names]
  data.table::set(dt, j = newval_names, value = newval_vals)
}